# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
import numpy as np
arr= np.arange(10)
arr1=np.reshape(arr,(2,5))
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [33]:
arr= np.arange(10)
arr1=np.reshape(arr,(2,5))
arr2=np.ones((2,5),dtype="int")
a=np.vstack((arr1,arr2))
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [35]:
arr= np.arange(10)
arr1=np.reshape(arr,(2,5))
arr2=np.ones((2,5),dtype="int")
a=np.hstack((arr1,arr2))
print(a)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [37]:
arr= np.arange(10)
arr1=np.reshape(arr,(2,5))
arr2=np.ravel(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [41]:
arr=np.random.randint(0,15,[5,3]) 
arr1=np.ravel(arr)
print(arr,arr1)

[[13 13  9]
 [ 0 14  5]
 [ 4  6  4]
 [ 0  5  4]
 [ 8  6 11]] [13 13  9  0 14  5  4  6  4  0  5  4  8  6 11]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [44]:
arr= np.arange(15)
arr1=np.reshape(arr,(3,5,1))
print(arr1)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [49]:
arr=np.random.randint(0,15,[5,3])
arr1=np.sqrt(arr) 
print(arr,arr1)

[[14 11  2]
 [ 1  2  7]
 [13  8  7]
 [13  1 10]
 [ 8  5 11]] [[3.74165739 3.31662479 1.41421356]
 [1.         1.41421356 2.64575131]
 [3.60555128 2.82842712 2.64575131]
 [3.60555128 1.         3.16227766]
 [2.82842712 2.23606798 3.31662479]]


## Question:8

### Create 5x6 an array and find the mean?

In [52]:
arr=np.random.randint(0,15,[5,3])
arr1=np.mean(arr) 
print(arr,arr1)

[[ 3  1  0]
 [ 5  6  7]
 [12 11  1]
 [13  5  1]
 [ 9  5  2]] 5.4


## Question:9

### Find the standard deviation of the previous array in Q8?

In [55]:
arr2=np.std(arr) 
print(arr,arr2)

[[ 3  1  0]
 [ 5  6  7]
 [12 11  1]
 [13  5  1]
 [ 9  5  2]] 4.111771718695807


## Question:10

### Find the median of the previous array in Q8?

In [57]:
arr2=np.median(arr) 
print(arr,arr2)

[[ 3  1  0]
 [ 5  6  7]
 [12 11  1]
 [13  5  1]
 [ 9  5  2]] 5.0


## Question:11

### Find the transpose of the previous array in Q8?

In [59]:
arr2=arr.T 
print(arr)
print(arr2)

[[ 3  1  0]
 [ 5  6  7]
 [12 11  1]
 [13  5  1]
 [ 9  5  2]]
[[ 3  5 12 13  9]
 [ 1  6 11  5  5]
 [ 0  7  1  1  2]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [61]:
arr=np.random.randint(0,15,[4,4])
arr3=np.trace(arr)
print(arr)
print(arr3)

[[12  5  6 10]
 [ 6 13  5  0]
 [10 10 10 13]
 [ 9  3  6  7]]
42


## Question:13

### Find the determinant of the previous array in Q12?

In [63]:

arr4=np.linalg.det(arr)
print(arr4)

-1961.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [67]:
arr=np.random.randint(0,15,[4,4])
ar5=np.percentile(arr,5)
ar95=np.percentile(arr,95)
print(ar5,ar95)

0.75 14.0 [[ 3  6  7 12]
 [13 12 14 14]
 [ 6 14  0  2]
 [ 1 10  5 14]]


## Question:15

### How to find if a given array has any null values?

In [84]:
a=np.nan
d=np.array([[1,2,3],[np.nan,6,7]]) 
print(d)
np.isnan(d)

[[ 1.  2.  3.]
 [nan  6.  7.]]


array([[False, False, False],
       [ True, False, False]])