# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
arr1=np.empty(10)
print(arr1)

[1.39806873e-152 4.78104754e+180 3.94147203e+180 2.42776530e-154
 2.28896090e+243 2.47379808e-091 2.44041296e-154 4.03536132e+087
 2.85763814e+161 6.01347002e-154]


3. Create a vector with values ranging from 10 to 49

In [13]:
arr2=np.random.randint(10,49,10) 


4. Find the shape of previous array in question 3

In [11]:
arr2=np.random.randint(10,49,10) 
arr2.shape

(10,)

5. Print the type of the previous array in question 3

In [12]:
print(arr2)

[37 19 29 21 36 19 25 38 34 18]


6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)

7. Print the dimension of the array in question 3


In [14]:
arr2.ndim

1

8. Create a boolean array with all the True values

In [20]:
arr3=np.ones([3,2],dtype="bool")
print(arr3)

[[ True  True]
 [ True  True]
 [ True  True]]


9. Create a two dimensional array




In [23]:
arr4=np.ones([3,3])
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


10. Create a three dimensional array



In [24]:
arr5=np.ones([3,3,3])
print(arr5)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [26]:
arr6=np.arange(10)
fliped=np.flip(arr6)
print(fliped)

[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [32]:
arr7=np.empty(10,dtype='int')
arr7[4]=5
print(arr7)

[ 1936028789  1819308832   543518313  1937008998           5   543912801
 -1526726491     7904632 -1385204080         680]


13. Create a 3x3 identity matrix

In [35]:
arr8=np.eye(3)
print(arr8)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [39]:
arr9=np.array([1, 2, 3, 4, 5],dtype='float')
print(arr9)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [40]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr10=arr1*arr2
print(arr10)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [42]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3= arr1>arr2
print(arr3)

[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [60]:
arr1=np.arange(20)
arr2=arr1/2
remainder, whole_part = np.modf(arr2)
target=np.where(remainder>0)
print(arr1[target[0]])

[ 1  3  5  7  9 11 13 15 17 19]


18. Replace all odd numbers to -1 from previous array

In [61]:
arr1=np.arange(20)
arr2=arr1/2
remainder, whole_part = np.modf(arr2)
target=np.where(remainder>0)
arr1[target[0]]=-1
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [82]:
arr = np.arange(10)
arr[5:9]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [83]:
arr=np.ones([4,4])
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [89]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [93]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:]=64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [100]:
arr=np.arange(10)
arr2d=arr.reshape(2,5)
print(arr2d)
print(arr2d[0])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [101]:
arr=np.arange(10)
arr2d=arr.reshape(2,5)
print(arr2d)
print(arr2d[0,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
1


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [102]:
arr=np.arange(10)
arr2d=arr.reshape(2,5)
print(arr2d)
print(arr2d[:,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [110]:
arr=np.random.randint(0,100,[10,10])
print(np.amax(arr))
print(np.amin(arr))


98
0


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [116]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
como=np.where(a==b)
print(a[como])

[2 2 4 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [117]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
como=np.where(a==b)
print(como[0])

[1 3 5 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [127]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
pos= np.where(names=='Will')
print(pos[0])
print(data[pos[0]])

[2 4]
[[ 0.15587203 -0.30514952 -0.33069691  1.0776208 ]
 [-0.15967654 -0.62425194  2.09852346  1.46171277]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [204]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
w=np.where((names != 'Joe') & (names != 'Will'))
ar=data[w[0]]
print(ar)
print(data)

[[-1.60234261  0.26635847 -0.61236006 -0.5370917 ]
 [ 0.57252968 -1.91963786  1.66858042  1.5014308 ]]
[[-1.60234261  0.26635847 -0.61236006 -0.5370917 ]
 [-0.46054731  0.21801821  1.73326224  1.38757293]
 [-0.52555715  2.2054281   1.95345112  0.29908661]
 [ 0.57252968 -1.91963786  1.66858042  1.5014308 ]
 [-0.98741561  0.52065023  0.28717747  0.70645921]
 [-0.67909806 -0.35282732 -1.70181938 -0.57660118]
 [ 0.60060079  0.48501526 -0.89605589  0.74205209]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [151]:
arr=np.random.randint(1,15,[5,3])
print(arr)

[[13  2  3]
 [13 11  2]
 [ 6  5 11]
 [ 9  5  3]
 [11  1  9]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [152]:
arr=np.random.randint(1,16,[2,2,4])
print(arr)

[[[10 11 13  3]
  [ 5  4  6 14]]

 [[10  3 13  2]
  [ 9  4 12  3]]]


33. Swap axes of the array you created in Question 32

In [156]:
arr=np.random.randint(1,16,[2,2,4])
print(arr)
print(np.swapaxes(arr,0,1))

[[[ 3  7 13  6]
  [ 9  6 11  2]]

 [[ 5 13 15  5]
  [12 10  3 13]]]
[[[ 3  7 13  6]
  [ 5 13 15  5]]

 [[ 9  6 11  2]
  [12 10  3 13]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [164]:
arr=np.random.randint(1,16,10)
n=np.sqrt(arr)
pos=np.where
print(n)

[3.60555128 2.64575131 2.23606798 1.73205081 3.60555128 2.82842712
 2.23606798 1.73205081 1.41421356 1.73205081]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [212]:
arr=np.random.randint(1,16,12)
arr1=np.random.randint(1,16,12)
arr1max=[max(arr),max(arr1)]
print(arr1max,arr,arr1)

[13, 14] [13  3 13  4  1 12 13  6  5 13  8 11] [14  2  2 13 11  9  5  9 12  5  1 10]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [214]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uni= np.unique([names])
print(uni)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [217]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
uni= np.unique([a,b])
print(uni)

[1 2 3 4 5 6 7 8 9]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [225]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1,:]=newColumn
print(sampleArray )

[[34 43 73]
 [10 10 10]
 [53 94 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [228]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z= np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [234]:
arr=np.random.randint(1,16,10)
he=arr.cumsum(axis=0)
print(he,arr)

[ 1  3 16 26 28 40 55 64 66 70] [ 1  2 13 10  2 12 15  9  2  4]
